idf_component_register(SRCS "main.c" 
                        "aprs_web.c"
                        "mr_cfg.c"
                        "mr_wifi_sta.c"
                        "mr_wifi_ota.c"
                        "mr_wifi_ota_web.c"
                        "mr_display.c"
                        "mr_time_net.c"
                        "mr_board.c"
                        "mr_gps.c"
                        "mr_pmu.c"
                        "mr_i2c_bus.c"
                        "aprs.c"
                        "aprs_web.c"
                        "bme280.c"
                    INCLUDE_DIRS ".")