#include "incl/mr_web_ui.h"
#include "incl/mr_web_cmdcfg.h"

#include <stdio.h>
#include <string.h>

static char s_html[32768];

const char *mr_web_ui_html(void)
{
    const char *cmd_html = mr_web_cmdcfg_html();
    const char *cmd_js   = mr_web_cmdcfg_js();

    snprintf(s_html, sizeof(s_html),
"<!doctype html><html><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>MeshRadio Bonus Software</title>"
"<style>"
"body{font-family:system-ui;margin:8px;max-width:1280px;background:#f7f7f8}"
"button{padding:10px 14px;margin:6px 4px;font-size:16px}"
"input:not([type='checkbox']){padding:10px;margin:6px 0;font-size:16px;width:100%%;box-sizing:border-box}"
"input[type='checkbox']{width:16px;height:16px;margin:0;padding:0}"
"select{padding:10px;margin:6px 0;font-size:16px;width:100%%;box-sizing:border-box}"
".card{border:1px solid #d7d7db;border-radius:14px;padding:12px;background:#fff;box-shadow:0 1px 2px rgba(0,0,0,.04);margin:8px 0}"
".muted{color:#666}.err{color:#b00020;font-weight:600}.ok{color:#0b7a26;font-weight:600}.warn{color:#b36b00;font-weight:600}"
".grid{display:grid;grid-template-columns:1fr;gap:12px}"
".controls-grid{display:grid;grid-template-columns:1fr;gap:10px}"
".triple-grid{display:grid;grid-template-columns:1fr;gap:10px}"
".double-grid{display:grid;grid-template-columns:1fr;gap:10px}"
"@media(min-width:980px){.grid{grid-template-columns:1fr 1fr 1fr}.triple-grid{grid-template-columns:1fr 1fr 1fr}.double-grid{grid-template-columns:1fr 1fr}}"
".cfg-checks{display:grid;grid-template-columns:1fr;row-gap:10px;margin-bottom:14px}"
".cfg-checks label{display:grid;grid-template-columns:20px auto;column-gap:10px;align-items:center;justify-content:start;margin:0;white-space:nowrap}"
".cfg-actions{display:flex;flex-direction:column;gap:10px;margin-top:14px}"
".cfg-actions-row{display:flex;flex-wrap:wrap;gap:10px}"
".cfg-actions button{margin:0}"
".cfg-three{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px}"
".cfg-three-wide{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;margin-top:10px}"
".cfg-cmd-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}"
".status-grid{display:grid;grid-template-columns:1fr;gap:12px}"
".mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap}"
".amp{display:inline-block;width:14px;height:14px;border-radius:999px;background:#6b7280;vertical-align:middle;margin-right:8px}"
".statusline{font-size:15px;margin:4px 0}"
".statusline b{font-weight:700}"
".pill{display:inline-block;padding:2px 8px;border:1px solid #ddd;border-radius:999px;background:#fafafa;margin-right:6px}"
".section-title{font-size:14px;font-weight:700;margin:0 0 10px 0}"
".inline-buttons button{margin:4px 6px 0 0}"
".table-wrap{overflow:auto}"
"table{width:100%%;border-collapse:collapse;margin-top:8px;background:#fff}"
"th,td{border:1px solid #ddd;padding:6px;text-align:left;font-size:14px}"
"th{background:#f3f4f6}"
".pw-wrap{display:flex;gap:8px;align-items:center}"
".pw-wrap input{flex:1}"
".pw-eye{padding:8px 10px;font-size:14px}"
".top-meta{font-size:12px;color:#666;margin-bottom:6px}"
".navrow{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px}"
"@media(max-width:980px){.cfg-three,.cfg-three-wide,.cfg-cmd-grid,.status-grid{grid-template-columns:1fr}}"
"</style></head><body>"

"<div class='top-meta'>MeshRadio Web UI v2 – https://nerdverlag.com (c) 2026</div>"

"<div class='card'>"
"  <div><span id='amp' class='amp'></span><b>UI-Ampel:</b> <span id='ampText'>NO RX</span></div>"
"  <div class='statusline'><b>Status:</b> <span id='sub'>loading...</span></div>"
"  <div class='statusline'><b>Target:</b> <span id='st'>loading...</span> / Firmware: <span id='version'>-</span> / Protokoll: <span id='proto'>-</span></div>"
"  <div id='err' class='err' style='margin-top:6px'></div>"
"  <div style='margin-top:10px'>"
"    <button onclick='refreshAll()'>Refresh</button>"
"  </div>"
"</div>"

"<div class='triple-grid'>"
"  <div class='card' id='send_section'>"
"    <h3 class='section-title'>DATA senden</h3>"
"    <label>Ziel (dst)</label>"
"    <input id='dst' placeholder='z.B. DJ2RF'>"
"    <label>ACK (0/1)</label>"
"    <input id='ackreq' value='1'>"
"    <label>Text</label>"
"    <input id='msg' placeholder='Nachricht'>"
"    <label>Quick Command</label>"
"    <select id='quick_select' onchange='applyQuickSelect()'>"
"      <option value=''>-- Select Command --</option>"
"      <option value='CMD:STATUS?'>STATUS</option>"
"      <option value='CMD:DISPLAY ON'>DISPLAY ON</option>"
"      <option value='CMD:DISPLAY OFF'>DISPLAY OFF</option>"
"      <option value='CMD:WIFI ON'>WIFI ON</option>"
"      <option value='CMD:WIFI OFF'>WIFI OFF</option>"
"      <option value='CMD:GPS'>GPS</option>"
"      <option value='CMD:BATT'>BATT</option>"
"      <option value='CMD:VERSION'>VERSION</option>"
"      <option value='CMD:REBOOT'>REBOOT</option>"
"      <option value='CMD:RELAY ON'>RELAY ON</option>"
"      <option value='CMD:RELAY OFF'>RELAY OFF</option>"
"      <option value='CMD:RELAY TOGGLE'>RELAY TOGGLE</option>"
"      <option value='CMD:CRYPTO ON'>CRYPTO ON</option>"
"      <option value='CMD:CRYPTO OFF'>CRYPTO OFF</option>"
"      <option value='CMD:BEACON ON'>BEACON ON</option>"
"      <option value='CMD:BEACON OFF'>BEACON OFF</option>"
"      <option value='CMD:ROUTEADV ON'>ROUTEADV ON</option>"
"      <option value='CMD:ROUTEADV OFF'>ROUTEADV OFF</option>"
"      <option value='CMD:DISPLAY CLEAR'>DISPLAY CLEAR</option>"
"      <option value='CMD:DISPLAY TEST'>DISPLAY TEST</option>"
"    </select>"
"    <div><button onclick='sendData()'>SEND</button></div>"
"    <div id='sendmsg' class='muted'></div>"
"  </div>"

"  <div class='card'>"
"    <h3 class='section-title'>Node Role</h3>"
"    <div class='statusline'><b>Mode:</b> <span id='modeTxt' class='ok'>-</span></div>"
"    <div class='inline-buttons'>"
"      <button onclick='setNodeMode(0)'>RELAY</button>"
"      <button onclick='setNodeMode(1)'>EDGE</button>"
"      <button onclick='setNodeMode(2)'>SENSOR</button>"
"    </div>"
"  </div>"

"  <div class='card'>"
"    <h3 class='section-title'>Security</h3>"
"    <div class='statusline'><b>Crypto:</b> <span id='cryptoTxt' class='warn'>-</span></div>"
"    <div class='inline-buttons'>"
"      <button onclick='setBoolCfg(\"crypto\",1)'>Crypto ON</button>"
"      <button onclick='setBoolCfg(\"crypto\",0)'>Crypto OFF</button>"
"    </div>"
"  </div>"

"  <div class='card'>"
"    <h3 class='section-title'>WiFi / Web UI</h3>"
"    <div class='inline-buttons'>"
"      <button onclick='setWifiUi(true)'>WiFi ON</button>"
"      <button onclick='setWifiUi(false)'>WiFi OFF</button>"
"    </div>"
"  </div>"

"  <div class='card'>"
"    <h3 class='section-title'>Relay Output</h3>"
"    <div class='inline-buttons'>"
"      <button onclick='relaySet(true)'>Relay ON</button>"
"      <button onclick='relaySet(false)'>Relay OFF</button>"
"      <button onclick='relayToggleDirect()'>Relay TOGGLE</button>"
"    </div>"
"  </div>"

"  <div class='card'>"
"    <h3 class='section-title'>APRS</h3>"
"    <div class='inline-buttons'>"
"      <button onclick='location.href=\"/aprs\"'>APRS Config</button>"
"    </div>"
"  </div>"
"</div>"

"<div class='double-grid'>"
"  <div class='card'>"
"    <h3 class='section-title'>Last RX</h3>"
"    <div id='lastrx' class='mono'></div>"
"  </div>"

"  <div class='card'>"
"    <h3 class='section-title'>Statistik</h3>"
"    <div id='status_counters' class='mono'></div>"
"    <div id='status_secstats' class='mono' style='margin-top:10px'></div>"
"  </div>"
"</div>"

"<div class='double-grid'>"
"  <div class='card'>"
"    <h3 class='section-title'>Neighbors</h3>"
"    <div id='neigh'><span class='muted'>loading...</span></div>"
"  </div>"

"  <div class='card'>"
"    <h3 class='section-title'>Routes</h3>"
"    <div id='routes'><span class='muted'>loading...</span></div>"
"  </div>"
"</div>"
"<div class='card' id='cfg_section'>"
"<div style='display:flex;justify-content:space-between;align-items:center'>"
"  <h3 style='margin:0'>Configuration</h3>"
"  <a href='https://nerdverlag.com/?page_id=706' target='_blank'>"
"    <button style='padding:8px 20px;font-size:14px;font-weight:bold;color:#fff;background:#d00000;border:1px solid #900;border-radius:6px'>HELP</button>"
"  </a>"
"</div>"

"  <div class='grid'>"
"    <div>"
"      <label>Callsign</label><input id='cfg_callsign'>"
"      <label>Relay Callsign</label><input id='cfg_relay_callsign'>"
"      <label>Node Mode</label>"
"      <select id='cfg_node_mode'>"
"        <option value='0'>RELAY</option>"
"        <option value='1'>EDGE</option>"
"        <option value='2'>SENSOR</option>"
"      </select>"
"      <label>RF Frequency (Hz)</label><input id='cfg_rf_hz'>"
"      <label>TX Power (dBm)</label><input id='cfg_tx_dbm'>"
"      <label>Beacon Interval (ms)</label><input id='cfg_beacon_ms'>"
"      <label>Holddown (ms)</label><input id='cfg_holddown_ms'>"
"    </div>"

"    <div>"
"      <label>WiFi AP SSID</label><input id='cfg_ssid'>"
"      <label>WiFi AP Password</label>"
"      <div class='pw-wrap'><input id='cfg_pass' type='password'><button type='button' class='pw-eye' onclick='togglePwBtn(\"cfg_pass\", this)'>👁</button></div>"
"      <label>Router STA SSID</label><input id='cfg_sta_ssid'>"
"      <label>Router STA Password</label>"
"      <div class='pw-wrap'><input id='cfg_sta_pass' type='password'><button type='button' class='pw-eye' onclick='togglePwBtn(\"cfg_sta_pass\", this)'>👁</button></div>"
"      <label>Net ID</label><input id='cfg_net_id'>"
"      <label>Net Key (32 hex)</label><input id='cfg_netkey'>"
"      <div class='cfg-three'>"
"        <div><label>RouteAdv TopN</label><input id='cfg_routeadv_topn'></div>"
"        <div><label>Relay GPIO</label><input id='cfg_relay_gpio'></div>"
"        <div></div>"
"      </div>"
"    </div>"

"    <div>"
"      <div class='cfg-checks'>"
"        <label><input type='checkbox' id='cfg_wifi'><span>WiFi enabled</span></label>"
"        <label><input type='checkbox' id='cfg_crypto'><span>Crypto enabled</span></label>"
"        <label><input type='checkbox' id='cfg_beacon'><span>Beacon enabled</span></label>"
"        <label><input type='checkbox' id='cfg_routeadv'><span>RouteAdv enabled</span></label>"
"        <label><input type='checkbox' id='cfg_cad'><span>CAD enabled</span></label>"
"        <label><input type='checkbox' id='cfg_powersave'><span>PowerSave enabled</span></label>"
"        <label><input type='checkbox' id='cfg_bme280'><span>BME280 enabled</span></label>"
"        <label><input type='checkbox' id='cfg_display'><span>Display enabled</span></label>"
"        <label><input type='checkbox' id='cfg_cmd_enable'><span>Command Trigger enabled</span></label>"
"      </div>"
"      <div class='cfg-actions'>"
"        <div class='cfg-actions-row'>"
"          <button onclick='cfgApplyForm()'>Apply Form</button>"
"          <button onclick='cfgSave()'>Save NVS</button>"
"        </div>"
"        <div class='cfg-actions-row'>"
"          <button onclick='cfgLoad()'>Load NVS</button>"
"          <button onclick='cfgDefaults()'>Defaults</button>"
"        </div>"
"        <div class='cfg-actions-row'>"
"          <button onclick='cfgRefresh()'>Reload Config</button>"
"          <button style='font-weight:bold;color:#fff;background:#c00018;border:1px solid #7a0010' onclick='doReset()'>Reset ESP</button>"
"        </div>"
"        <div class='cfg-actions-row'>"
"          <button style='font-weight:bold;color:#fff;background:#a00000;border:1px solid #700' onclick='doFactoryReset()'>Factory Reset</button>"
"        </div>"
"      </div>"
"      <div id='cfgmsg' class='muted' style='margin-top:10px'></div>"
"    </div>"
"  </div>"

"  <div class='cfg-three-wide'>"
"    <div><label>RouteAdv Delta</label><input id='cfg_routeadv_delta'></div>"
"    <div><label>Sensor Wake (ms)</label><input id='cfg_sensor_wake_ms'></div>"
"    <div><label>Sensor RX Window (ms)</label><input id='cfg_sensor_rxwin_ms'></div>"
"  </div>"
"</div>"


"%s"

"<script>"
"async function post(url,body){"
"  let r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body||''});"
"  return await r.text();"
"}"

"function esc(s){"
"  return String(s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('\"','&quot;');"
"}"

"function renderTable(headers, rows){"
"  let h='<table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>';"
"  h += rows.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('');"
"  h += '</tbody></table>';"
"  return h;"
"}"

"function setAmp(color){"
"  let el=document.getElementById('amp');"
"  if(!el) return;"
"  el.style.background=color;"
"}"

"function togglePwBtn(inputId, btn){"
"  let inp=document.getElementById(inputId);"
"  if(!inp) return;"
"  let show = (inp.type === 'password');"
"  inp.type = show ? 'text' : 'password';"
"  if(btn) btn.textContent = show ? '🙈' : '👁';"
"}"

"async function cfgPost(key,val){"
"  return await post('/api/cfg','key='+encodeURIComponent(key)+'&val='+encodeURIComponent(val));"
"}"

"function cfgSetMsg(t){"
"  let el=document.getElementById('cfgmsg');"
"  if(el) el.textContent=t;"
"}"

"async function applyCfgAndRefresh(){"
"  let ra=await post('/api/cfg/apply','');"
"  await cfgRefresh();"
"  await refreshAll();"
"  return ra;"
"}"

"async function setBoolCfg(key,val){"
"  let r=await cfgPost(key, String(val));"
"  if(String(r).startsWith('OK')) await applyCfgAndRefresh();"
"  else document.getElementById('err').textContent='Config error: '+r;"
"}"

"async function setNodeMode(mode){"
"  let r=await cfgPost('node_mode', String(mode));"
"  if(String(r).startsWith('OK')) await applyCfgAndRefresh();"
"  else document.getElementById('err').textContent='Node mode error: '+r;"
"}"

"function applyQuickSelect(){"
"  let sel=document.getElementById('quick_select');"
"  if(sel && sel.value) document.getElementById('msg').value = sel.value;"
"}"

"async function relaySet(on){"
"  let r=await post('/api/relay', 'enable=' + (on ? '1' : '0'));"
"  document.getElementById('sendmsg').textContent = r;"
"  setTimeout(refreshAll, 300);"
"}"

"async function relayToggleDirect(){"
"  let r=await post('/api/relay/toggle', '');"
"  document.getElementById('sendmsg').textContent = r;"
"  setTimeout(refreshAll, 300);"
"}"

"async function sendQuick(cmd){"
"  document.getElementById('msg').value=cmd;"
"  await sendData();"
"  setTimeout(refreshAll, 500);"
"}"

"async function setWifiUi(on){"
"  let r=await cfgPost('wifi', on ? '1' : '0');"
"  if(String(r).startsWith('OK')){"
"    document.getElementById('sendmsg').textContent = on ? 'WiFi/Web UI wird aktiviert...' : 'WiFi/Web UI wird deaktiviert...';"
"    await post('/api/cfg/apply','');"
"    setTimeout(refreshAll, 500);"
"  } else {"
"    document.getElementById('err').textContent='WiFi config error: '+r;"
"  }"
"}"


"%s"

"async function cfgRefresh(){"
"  try{"
"    let resp = await fetch('/api/cfg');"
"    let txt = await resp.text();"
"    if(!txt.startsWith('{')) throw new Error(txt);"
"    let c = JSON.parse(txt);"
"    document.getElementById('cfg_callsign').value=c.callsign||'';"
"    document.getElementById('cfg_relay_callsign').value=c.relay_callsign||'';"
"    document.getElementById('cfg_node_mode').value=String(c.node_mode ?? 0);"
"    document.getElementById('cfg_rf_hz').value=c.rf_hz ?? '';"
"    document.getElementById('cfg_tx_dbm').value=c.tx_dbm ?? '';"
"    document.getElementById('cfg_beacon_ms').value=c.beacon_ms ?? '';"
"    document.getElementById('cfg_holddown_ms').value=c.holddown_ms ?? '';"
"    document.getElementById('cfg_ssid').value=c.ssid||'';"
"    document.getElementById('cfg_sta_ssid').value=c.sta_ssid||'';"
"    document.getElementById('cfg_net_id').value=c.net_id ?? '';"
"    document.getElementById('cfg_netkey').value='';"
"    document.getElementById('cfg_relay_gpio').value=c.relay_gpio ?? '';"
"    document.getElementById('cfg_routeadv_topn').value=c.routeadv_topn ?? '';"
"    document.getElementById('cfg_routeadv_delta').value=c.routeadv_delta ?? '';"
"    document.getElementById('cfg_sensor_wake_ms').value=c.sensor_wake_ms ?? '';"
"    document.getElementById('cfg_sensor_rxwin_ms').value=c.sensor_rxwin_ms ?? '';"
"    document.getElementById('cfg_wifi').checked=!!c.wifi;"
"    document.getElementById('cfg_crypto').checked=!!c.crypto;"
"    document.getElementById('cfg_beacon').checked=!!c.beacon;"
"    document.getElementById('cfg_routeadv').checked=!!c.routeadv;"
"    document.getElementById('cfg_cad').checked=!!c.cad;"
"    document.getElementById('cfg_powersave').checked=!!c.powersave;"
"    document.getElementById('cfg_bme280').checked=!!c.bme280;"
"    document.getElementById('cfg_display').checked=!!c.display;"
"    cmdCfgRefresh(c);"
"    cfgSetMsg('Config loaded');"
"  }catch(e){"
"    cfgSetMsg('Config load error: '+e);"
"  }"
"}"

"async function cfgApplyForm(){"
"  try{"
"    let ops=["
"      ['callsign', document.getElementById('cfg_callsign').value],"
"      ['relay_callsign', document.getElementById('cfg_relay_callsign').value],"
"      ['node_mode', document.getElementById('cfg_node_mode').value],"
"      ['rf_hz', document.getElementById('cfg_rf_hz').value],"
"      ['tx_dbm', document.getElementById('cfg_tx_dbm').value],"
"      ['beacon_ms', document.getElementById('cfg_beacon_ms').value],"
"      ['holddown_ms', document.getElementById('cfg_holddown_ms').value],"
"      ['ssid', document.getElementById('cfg_ssid').value],"
"      ['sta_ssid', document.getElementById('cfg_sta_ssid').value],"
"      ['netid', document.getElementById('cfg_net_id').value],"
"      ['relay_gpio', document.getElementById('cfg_relay_gpio').value],"
"      ['routeadv_topn', document.getElementById('cfg_routeadv_topn').value],"
"      ['routeadv_delta', document.getElementById('cfg_routeadv_delta').value],"
"      ['sensor_wake_ms', document.getElementById('cfg_sensor_wake_ms').value],"
"      ['sensor_rxwin_ms', document.getElementById('cfg_sensor_rxwin_ms').value],"
"      ['wifi', document.getElementById('cfg_wifi').checked ? '1' : '0'],"
"      ['crypto', document.getElementById('cfg_crypto').checked ? '1' : '0'],"
"      ['beacon', document.getElementById('cfg_beacon').checked ? '1' : '0'],"
"      ['routeadv', document.getElementById('cfg_routeadv').checked ? '1' : '0'],"
"      ['cad', document.getElementById('cfg_cad').checked ? '1' : '0'],"
"      ['powersave', document.getElementById('cfg_powersave').checked ? '1' : '0'],"
"      ['bme280', document.getElementById('cfg_bme280').checked ? '1' : '0'],"
"      ['display', document.getElementById('cfg_display').checked ? '1' : '0']"
"    ];"
"    let cmdOps = cmdCfgCollectOps();"
"    for(let kv of cmdOps) ops.push(kv);"
"    let pass=document.getElementById('cfg_pass').value;"
"    let sta_pass=document.getElementById('cfg_sta_pass').value;"
"    let netkey=document.getElementById('cfg_netkey').value;"
"    if(pass.length>0) ops.push(['pass', pass]);"
"    if(sta_pass.length>0) ops.push(['sta_pass', sta_pass]);"
"    if(netkey.length>0) ops.push(['netkey', netkey]);"
"    for(let kv of ops){"
"      let r=await cfgPost(kv[0], kv[1]);"
"      if(!String(r).startsWith('OK')){"
"        cfgSetMsg('Error at '+kv[0]+': '+r);"
"        return;"
"      }"
"    }"
"    let ra=await post('/api/cfg/apply','');"
"    cfgSetMsg(ra + ' - Konfiguration übernommen.');"
"    await cfgRefresh();"
"  }catch(e){"
"    cfgSetMsg('Apply error: '+e);"
"  }"
"}"

"async function cfgSave(){"
"  let r=await post('/api/cfg/save','');"
"  cfgSetMsg(r);"
"}"

"async function cfgLoad(){"
"  let r=await post('/api/cfg/load','');"
"  cfgSetMsg(r);"
"  await cfgRefresh();"
"}"

"async function cfgDefaults(){"
"  let r=await post('/api/cfg/defaults','');"
"  cfgSetMsg(r);"
"  await cfgRefresh();"
"}"

"async function doReset(){"
"  if(!confirm('ESP jetzt neu starten?')) return;"
"  let r=await post('/api/reset','');"
"  cfgSetMsg(r);"
"}"

"async function doFactoryReset(){"
"  if(!confirm('Factory Reset ausführen? NVS wird gelöscht und das Gerät startet neu.')) return;"
"  let r=await post('/api/cfg/erase','');"
"  cfgSetMsg(r);"
"}"

"async function sendData(){"
"  let dst=document.getElementById('dst').value;"
"  let msg=document.getElementById('msg').value;"
"  try{ localStorage.setItem('mr_last_dst', dst); }catch(_e){}"
"  let r=await post('/api/send','dst='+encodeURIComponent(dst)+'&msg='+encodeURIComponent(msg));"
"  document.getElementById('sendmsg').textContent=r;"
"  setTimeout(refreshAll, 500);"
"}"

"async function quickCmd(cmd){"
"  document.getElementById('msg').value=cmd;"
"  await sendData();"
"}"

"async function refreshAll(){"
"  try{"
"    let sj=JSON.parse(await (await fetch('/api/status')).text());"
"    let call = (sj.callsign || sj.call || '-');"
"    document.getElementById('st').textContent = (sj.board || '-') + ' / ' + (sj.chip || '-');"
"    document.getElementById('version').textContent = sj.version || sj.fw || '-';\n"
"    document.getElementById('proto').textContent = sj.proto || '-';"
"    document.getElementById('sub').textContent = 'call=' + call + ' · mode=' + (sj.node_mode_str || '-') + ' · display=' + (sj.display ? 'ON' : 'OFF') + ' · wifi=' + (sj.wifi ? 'ON' : 'OFF') + ' · relay=' + (sj.relay ? 'ON' : 'OFF') + ' · crypto=' + (sj.crypto_enable ? 'ON' : 'OFF') + ' · batt=' + (sj.batt || '-');"
"    document.getElementById('modeTxt').textContent = sj.node_mode_str || '-';"
"    document.getElementById('cryptoTxt').textContent = sj.crypto_enable ? 'ON' : 'OFF';"
"    document.getElementById('cryptoTxt').className = sj.crypto_enable ? 'ok' : 'warn';"
"    document.getElementById('status_counters').textContent = sj.counters || '';"
"    document.getElementById('status_secstats').textContent = sj.secstats || '';"
"    setAmp('#9ca3af','NO RX');"
"    document.getElementById('ampText').textContent='NO RX';"
"    document.getElementById('err').textContent='';"

"    let lj=JSON.parse(await (await fetch('/api/lastrx')).text());"
"    if(lj.age_ms < 0){"
"      document.getElementById('lastrx').innerHTML='<span class=muted>none</span>';"
"    }else{"
"      let age = lj.age_ms;"
"      document.getElementById('lastrx').innerHTML = '<b>from</b> <code>'+esc(lj.from)+'</code><br><b>text</b> '+esc(lj.text)+'<br><span class=muted>age_ms='+age+'</span>';"
"      if(age <= 6000){ setAmp('#19a34a','OK'); document.getElementById('ampText').textContent='RX OK'; }"
"      else if(age <= 20000){ setAmp('#f59e0b','STALE'); document.getElementById('ampText').textContent='STALE'; }"
"      else { setAmp('#dc2626','OLD'); document.getElementById('ampText').textContent='OLD'; }"
"    }"

"    let nj=JSON.parse(await (await fetch('/api/neighbors')).text());"
"    let nrows=nj.map(x=>[x.call, x.rssi, x.age_ms, x.tx_attempts, x.ack_ok, x.etx_x100]);"
"    document.getElementById('neigh').innerHTML = nrows.length ? renderTable(['call','rssi','age_ms','tx','ack','etx_x100'], nrows) : '<span class=muted>none</span>';"

"    let rj=JSON.parse(await (await fetch('/api/routes')).text());"
"    let rrows=rj.map(x=>[x.dst, x.next, x.etx_x100, x.seq, x.age_ms, x.hold_ms]);"
"    document.getElementById('routes').innerHTML = rrows.length ? renderTable(['dst','next','etx_x100','seq','age_ms','hold_ms'], rrows) : '<span class=muted>none</span>';"
"  }catch(e){"
"    document.getElementById('st').textContent='ERROR';"
"    document.getElementById('err').textContent='Dashboard error: '+e;"
"    setAmp('#dc2626','UI ERROR');"
"    document.getElementById('ampText').textContent='UI ERROR';"
"  }"
"}"

"let lastDst = localStorage.getItem('mr_last_dst');"
"if(lastDst) document.getElementById('dst').value = lastDst;"
"else document.getElementById('dst').value = 'DJ2RF';"
"cfgRefresh();"
"refreshAll();"
"setInterval(refreshAll, 3000);"
"</script></body></html>",
        cmd_html,
        cmd_js
    );

    return s_html;
}
